CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    date DATE,
    time TIME
);

create table pizza_Types
(
	 pizza_type_id VARCHAR(50) PRIMARY KEY,
     name VARCHAR(100),
     category VARCHAR(50),
     ingredients TEXT
)


create table pizzas
(
    pizza_id VARCHAR(50) PRIMARY KEY,
    pizza_type_id VARCHAR(50),
    size VARCHAR(10),
    price DECIMAL(5,2),
    FOREIGN KEY (pizza_type_id)
        REFERENCES pizza_types(pizza_type_id)

);


create table order_details
(
	order_details_id INT PRIMARY KEY,
    order_id INT,
    pizza_id VARCHAR(50),
    quantity INT,
    FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    FOREIGN KEY (pizza_id)
        REFERENCES pizzas(pizza_id)
);

/* 
Data Import:
- Created all required tables in PostgreSQL.
- Imported the CSV files directly using PostgreSQL's Import/Export feature.
- Enabled the "Header" option while importing.
- Converted the pizza_types.csv file to UTF-8 encoding to resolve the encoding error.
- Successfully imported all four datasets:
    • orders
    • order_details
    • pizzas
    • pizza_types
*/

select * from orders
select * from pizza_types
select * from pizzas
select * from order_details

-- Retrieve the total number of orders placed.
select count(order_id) as total_order from orders

-- Display the names of pizzas that belong to the 'Chicken' category and cost more than 20.
select pt.name,p.price from pizza_types as pt 
join pizzas as p 
on pt.pizza_type_id=p.pizza_type_id 
where pt.category='Chicken' 
and p.price>20

--Display the total revenue generated by each pizza size.

select p.size,sum(p.price*od.quantity)as total_revenue 
from order_details as od 
join pizzas as p
on p.pizza_id=od.pizza_id
group by p.size

-- Calculate the total revenue generated from pizza sales.
SELECT 
SUM(p.price * od.quantity) AS total_revenue
FROM pizzas AS p
JOIN order_details AS od
ON p.pizza_id = od.pizza_id;

-- Identify the highest-priced pizza.
select pt.name,p.price from 
pizza_types as pt join pizzas as p  
on pt.pizza_type_id=p.pizza_type_id
order by p.price desc limit 1

-- Identify the most common pizza size ordered.
select p.size,count(o.order_details_id) as total_orders  
from pizzas as p 
join order_details as o 
on p.pizza_id=o.pizza_id  
group by  p.size 
order by total_orders desc 
limit 1

-- List the top 5 most ordered pizza types along with their total quantities ordered.
select pt.name,sum(od.quantity) as total_quantity 
from pizza_types as pt 
join pizzas as p 
on pt.pizza_type_id=p.pizza_type_id 
join order_details as od 
on p.pizza_id=od.pizza_id 
group by pt.name 
order by total_quantity desc 
limit 5 

-- Find the total quantity of each pizza category ordered. 
select pt.category,sum(od.quantity) as toal_quantity 
from pizza_types as pt  
join pizzas as p 
on pt.pizza_type_id=p.pizza_type_id 
join order_details as od  on 
p.pizza_id=od.pizza_id 
group by pt.category

-- Determine the distribution of orders by hour of the day.
SELECT EXTRACT(HOUR FROM time) AS hour,COUNT(order_id) AS total_orders 
FROM orders 
GROUP BY EXTRACT(HOUR FROM time)
ORDER BY hour;

-- Find the category-wise distribution of pizzas.
select category,count(name) as total_pizzas 
from pizza_types 
group by category 

-- Determine the top 3 most ordered pizza types based on revenue. 
select pt.name, sum(p.price * od.quantity) as revenue 
from pizza_types as pt 
join pizzas as p  
on pt.pizza_type_id=p.pizza_type_id 
join order_details as od 
on p.pizza_id=od.pizza_id
group by pt.name 
order by revenue 
desc 
limit 3

--Determine the average number of pizzas ordered per day
SELECT
    AVG(total_pizzas) AS average_pizzas_per_day
FROM
(
    SELECT
        o.date,
        SUM(od.quantity) AS total_pizzas
    FROM orders AS o
    JOIN order_details AS od
        ON o.order_id = od.order_id
    GROUP BY o.date
) AS daily_orders;

-- Find the names and prices of all pizzas whose price is greater than the average price of all pizzas.
select pt.name, p.price from pizza_types as pt 
join pizzas  as p 
on pt.pizza_type_id=p.pizza_type_id
where p.price >
(select avg(p.price) from pizzas as p)

--